-- Two additions from Claude Science's security review of the P8 seal
-- (2026-09-29): non-repudiation and tamper-evidence-by-construction, on top of
-- the existing SHA-256 integrity digest and append-by-policy audit trail.
-- Run once in the Supabase SQL editor.

-- 1. Ed25519 signature over p8_hash, binding a sealed run to LEON's signing
--    identity (see backend/routes/leon.py: sign_p8_seal / verify_p8_signature).
--    Null until LEON_SIGNING_PRIVATE_KEY is configured in the deployment --
--    null means "not yet signed", not "tampered".
alter table public.simulation_runs add column if not exists p8_signature text;

-- 2. Hash-chain the audit trail: a monotonic sequence column or ordering isn't
--    reliably derivable from a uuid primary key or created_at alone (timestamp
--    collisions are possible under concurrent writes), so an explicit identity
--    column anchors the chain order. chain_hash links each row to the previous
--    one's chain_hash (backend/routes/leon.py: _chain_hash / verify_chain) --
--    deleting or editing any row breaks the chain at every row after it,
--    detectably, regardless of what RLS policy is in force when someone checks.
alter table public.leon_audit add column if not exists seq bigint generated by default as identity;
alter table public.leon_audit add column if not exists chain_hash text;

create index if not exists leon_audit_seq_idx on public.leon_audit (seq);
